# Generated by Django 5.1 on 2024-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide_unique_label', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_format',
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
