# Generated by Django 5.1 on 2024-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide_unique_label', '0002_remove_problem_input_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=dict),
        ),
    ]
