# Generated by Django 5.1 on 2024-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide_unique_label', '0003_problem_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
    ]
